name: Feature Request
description: Suggest a new feature or enhancement for fixEcalendar
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature.
      placeholder: |
        As a user who...
        I want to...
        So that I can...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my workflow
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - PST file parsing
        - Calendar extraction
        - iCal export
        - CSV export
        - Database management
        - Command-line interface
        - Performance
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, show how you would use this feature.
      placeholder: |
        fixECalendar input.pst --new-option value
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request.
      placeholder: Any other information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: I have checked the documentation for existing functionality
          required: false
        - label: I am willing to help implement this feature
          required: false
